In [1]:
import os
os.chdir("..")
print(os.getcwd())

c:\Users\bradl\Documents\Projets Perso\real-estate-ai-agent

In [2]:
import polars as pl
from app.core.paths import SILVER_DIR
from app.data.utils import load_data_from_csv

# Import des données silver

In [5]:
dvf_sch = pl.Schema({
    "id_mutation": pl.String(),
    "date_mutation": pl.String(),
    "numero_disposition": pl.Int64(),
    "nature_mutation": pl.String(),	
    "valeur_fonciere": pl.Float64(),	
    "adresse_numero": pl.String(),	
    "adresse_nom_voie": pl.String(),	
    "code_postal": pl.String(),
    "code_commune": pl.String(),	
    "nom_commune": pl.String(),	
    "code_departement": pl.String(),	
    "type_local": pl.String(),
    "surface_reelle_bati": pl.Float64(),	
    "nombre_pieces_principales": pl.Int64(),
    "address_inferred_from_coords": pl.String(),	
    "is_valeur_fonciere_missing": pl.String(),
    "is_surface_missing": pl.String(),
    "is_nombre_pieces_missing": pl.String(),
    "is_surface_tres_faible": pl.String(),
    "is_valeur_fonciere_tres_basse": pl.String(),
    "is_appartement_sans_lot": pl.String(),
    "is_transaction_atypique_agent": pl.String()
})

In [3]:
bpe_sch = pl.Schema({
    "annee": pl.Int64,
    "code_postal": pl.String,
    "classification_n1": pl.String, 
    "classification_n2": pl.String,
    "classification_n3": pl.String,
    "nombre_equipements": pl.Int64 
})

In [6]:
dvf_silver = load_data_from_csv(SILVER_DIR, "dvf_silver.csv", sep=",", sch=dvf_sch)
bpe_silver = load_data_from_csv(SILVER_DIR, "bpe_silver.csv", sep=",", sch=bpe_sch)

2026-07-24 19:09:53.415 | INFO     | app.data.utils:load_data_from_csv:74 - Lecture du fichier CSV : C:\Users\bradl\Documents\Projets Perso\real-estate-ai-agent\data\silver\dvf_silver.csv
2026-07-24 19:09:53.477 | DEBUG    | app.data.utils:load_data_from_csv:79 - Fichier lu avec succès : 198751 lignes, 22 colonnes
2026-07-24 19:09:53.478 | INFO     | app.data.utils:load_data_from_csv:74 - Lecture du fichier CSV : C:\Users\bradl\Documents\Projets Perso\real-estate-ai-agent\data\silver\bpe_silver.csv
2026-07-24 19:09:53.488 | DEBUG    | app.data.utils:load_data_from_csv:79 - Fichier lu avec succès : 3773 lignes, 6 colonnes

In [6]:
dvf_silver = dvf_silver.with_columns(
    pl.col("date_mutation")
    .str.to_date(format="%Y-%m-%d", strict=True)
    .alias("date_mutation")
    )

In [7]:
dvf_silver.sample(5)

shape: (5, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ is_surfac ┆ is_valeur ┆ is_appart ┆ is_trans │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ e_tres_fa ┆ _fonciere ┆ ement_san ┆ action_a │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ible      ┆ _tres_bas ┆ s_lot     ┆ typique_ │
│ str       ┆ date      ┆ i64       ┆ str       ┆   ┆ ---       ┆ se        ┆ ---       ┆ agent    │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2021-1703 ┆ 2021-06-2 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 323       ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8219 ┆ 2020-08-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 00        ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-1342 ┆ 2023-03-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 776       ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021-1707 ┆ 2021-09-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 690       ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021-1706 ┆ 2021-09-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 936       ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
dvf_silver.filter(pl.col("id_mutation") == "2021-1682772")

shape: (1, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ address_i ┆ is_valeur ┆ is_surfac ┆ is_nombr │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ nferred_f ┆ _fonciere ┆ e_missing ┆ e_pieces │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ rom_coord ┆ _missing  ┆ ---       ┆ _missing │
│ str       ┆ date      ┆ i64       ┆ str       ┆   ┆ s         ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ str       ┆           ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2021-1682 ┆ 2021-02-1 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 772       ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
bpe_silver.sample(5)

shape: (5, 6)
┌───────┬─────────────┬───────────────────┬──────────────────┬──────────────────┬──────────────────┐
│ annee ┆ code_postal ┆ classification_n1 ┆ classification_n ┆ classification_n ┆ nombre_equipemen │
│ ---   ┆ ---         ┆ ---               ┆ 2                ┆ 3                ┆ ts               │
│ i64   ┆ str         ┆ str               ┆ ---              ┆ ---              ┆ ---              │
│       ┆             ┆                   ┆ str              ┆ str              ┆ i64              │
╞═══════╪═════════════╪═══════════════════╪══════════════════╪══════════════════╪══════════════════╡
│ 2024  ┆ 75016       ┆ Santé et action   ┆ Fonctions        ┆ Spécialiste en   ┆ 85               │
│       ┆             ┆ sociale           ┆ médicales et     ┆ ophtalmologie    ┆                  │
│       ┆             ┆                   ┆ paraméd…         ┆                  ┆                  │
│ 2024  ┆ 75013       ┆ Sports, loisirs   ┆ Equipements      ┆ Salles de remise ┆ 21               │
│       ┆             ┆ et culture        ┆ sportifs         ┆ en forme         ┆                  │
│ 2024  ┆ 75009       ┆ Santé et action   ┆ Fonctions        ┆ Spécialiste en   ┆ 13               │
│       ┆             ┆ sociale           ┆ médicales et     ┆ dermatologie vé… ┆                  │
│       ┆             ┆                   ┆ paraméd…         ┆                  ┆                  │
│ 2024  ┆ 75004       ┆ Sports, loisirs   ┆ Equipements      ┆ Plateaux et      ┆ 4                │
│       ┆             ┆ et culture        ┆ sportifs         ┆ terrains de jeux ┆                  │
│       ┆             ┆                   ┆                  ┆ e…               ┆                  │
│ 2024  ┆ 75008       ┆ Services pour les ┆ Autres services  ┆ Agence           ┆ 1418             │
│       ┆             ┆ particuliers      ┆                  ┆ immobilière      ┆                  │
└───────┴─────────────┴───────────────────┴──────────────────┴──────────────────┴──────────────────┘

In [ ]:
dvf_silver.filter((pl.col("is_valeur_fonciere_missing")) & (pl.col("is_surface_missing")))

shape: (557, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ is_surfac ┆ is_valeur ┆ is_appart ┆ is_trans │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ e_tres_fa ┆ _fonciere ┆ ement_san ┆ action_a │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ible      ┆ _tres_bas ┆ s_lot     ┆ typique_ │
│ str       ┆ date      ┆ i64       ┆ str       ┆   ┆ ---       ┆ se        ┆ ---       ┆ agent    │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2020-8148 ┆ 2020-08-1 ┆ 2         ┆ Adjudicat ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 33        ┆ 9         ┆           ┆ ion       ┆   ┆           ┆           ┆           ┆          │
│ 2020-8281 ┆ 2020-09-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 37        ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8309 ┆ 2020-11-3 ┆ 1         ┆ Vente en  ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 93        ┆ 0         ┆           ┆ l'état    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ futur     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ d'achève… ┆   ┆           ┆           ┆           ┆          │
│ 2020-8310 ┆ 2020-11-3 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 80        ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8310 ┆ 2020-11-3 ┆ 3         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 82        ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2021-1703 ┆ 2021-06-2 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 071       ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021-1715 ┆ 2021-09-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 557       ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021-1715 ┆ 2021-09-0 ┆ 2         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 557       ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021-1715 ┆ 2021-09-0 ┆ 2         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 557       ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2021-1708 ┆ 2021-08-2 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ false     ┆ false    │
│ 258       ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
dvf_silver.null_count()

shape: (1, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ is_surfac ┆ is_valeur ┆ is_appart ┆ is_trans │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ e_tres_fa ┆ _fonciere ┆ ement_san ┆ action_a │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ible      ┆ _tres_bas ┆ s_lot     ┆ typique_ │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ ---       ┆ se        ┆ ---       ┆ agent    │
│           ┆           ┆           ┆           ┆   ┆ u32       ┆ ---       ┆ u32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ u32       ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Construction gold_transactions

### 1. Colonnes Prix m² et surface totale

In [7]:
gold_transactions = dvf_silver.clone()

In [8]:
prix_m2_df = (
    gold_transactions
    .group_by(["id_mutation","numero_disposition"], maintain_order=True)
    .agg(pl.col("valeur_fonciere"),pl.sum("surface_reelle_bati").alias("surface_totale"))
              )

prix_m2_df = prix_m2_df.with_columns(
    pl.col("valeur_fonciere").list.unique().list.item().alias("valeur_fonciere")
)

prix_m2_df

shape: (124_455, 4)
┌─────────────┬────────────────────┬─────────────────┬────────────────┐
│ id_mutation ┆ numero_disposition ┆ valeur_fonciere ┆ surface_totale │
│ ---         ┆ ---                ┆ ---             ┆ ---            │
│ str         ┆ i64                ┆ f64             ┆ f64            │
╞═════════════╪════════════════════╪═════════════════╪════════════════╡
│ 2020-815165 ┆ 1                  ┆ 1.26e8          ┆ 0.0            │
│ 2020-814507 ┆ 1                  ┆ 45000.0         ┆ 0.0            │
│ 2020-814508 ┆ 1                  ┆ 148000.0        ┆ 12.0           │
│ 2020-814509 ┆ 1                  ┆ 90000.0         ┆ 0.0            │
│ 2020-814510 ┆ 1                  ┆ 270000.0        ┆ 27.0           │
│ …           ┆ …                  ┆ …               ┆ …              │
│ 2025-502878 ┆ 1                  ┆ 575000.0        ┆ 66.0           │
│ 2025-502879 ┆ 2                  ┆ 708809.0        ┆ 130.0          │
│ 2025-502880 ┆ 1                  ┆ 550000.0        ┆ 61.0           │
│ 2025-502881 ┆ 1                  ┆ 550386.1        ┆ 47.0           │
│ 2025-502882 ┆ 1                  ┆ 2.441758e7      ┆ 0.0            │
└─────────────┴────────────────────┴─────────────────┴────────────────┘

In [9]:
prix_m2_df = prix_m2_df.with_columns(
    pl.when(pl.col("surface_totale") != 0)
    .then(pl.col("valeur_fonciere")/pl.col("surface_totale"))
    .otherwise(None)
    .alias("prix_m2")
)

In [40]:
prix_m2_df.null_count()

shape: (1, 5)
┌─────────────┬────────────────────┬─────────────────┬────────────────┬─────────┐
│ id_mutation ┆ numero_disposition ┆ valeur_fonciere ┆ surface_totale ┆ prix_m2 │
│ ---         ┆ ---                ┆ ---             ┆ ---            ┆ ---     │
│ u32         ┆ u32                ┆ u32             ┆ u32            ┆ u32     │
╞═════════════╪════════════════════╪═════════════════╪════════════════╪═════════╡
│ 0           ┆ 0                  ┆ 115             ┆ 0              ┆ 19496   │
└─────────────┴────────────────────┴─────────────────┴────────────────┴─────────┘

In [10]:
gold_transactions = gold_transactions.join(prix_m2_df.drop("valeur_fonciere"),
                                           left_on=["id_mutation","numero_disposition"],
                                           right_on=["id_mutation","numero_disposition"],
                                           how="left",
                                           validate="m:1")

In [47]:
gold_transactions

shape: (198_751, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_mutati ┆ date_muta ┆ numero_di ┆ nature_mu ┆ … ┆ is_appart ┆ is_transa ┆ surface_t ┆ prix_m2  │
│ on        ┆ tion      ┆ sposition ┆ tation    ┆   ┆ ement_san ┆ ction_aty ┆ otale     ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ s_lot     ┆ pique_age ┆ ---       ┆ f64      │
│ str       ┆ date      ┆ i64       ┆ str       ┆   ┆ ---       ┆ nt        ┆ f64       ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2020-8151 ┆ 2020-10-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ 0.0       ┆ null     │
│ 65        ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ 0.0       ┆ null     │
│ 07        ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ 12.0      ┆ 12333.33 │
│ 08        ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3333     │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ 0.0       ┆ null     │
│ 09        ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2020-8145 ┆ 2020-07-0 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ 27.0      ┆ 10000.0  │
│ 10        ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-5028 ┆ 2025-06-2 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ 61.0      ┆ 9016.393 │
│ 80        ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 443      │
│ 2025-5028 ┆ 2025-06-2 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ 61.0      ┆ 9016.393 │
│ 80        ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 443      │
│ 2025-5028 ┆ 2025-06-2 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ 47.0      ┆ 11710.34 │
│ 81        ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2553     │
│ 2025-5028 ┆ 2025-06-2 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ 47.0      ┆ 11710.34 │
│ 81        ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2553     │
│ 2025-5028 ┆ 2025-06-2 ┆ 1         ┆ Vente     ┆ … ┆ false     ┆ false     ┆ 0.0       ┆ null     │
│ 82        ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### 2. Colonnes en lien avec le type de bien

In [11]:
local_df = dvf_silver.group_by(["id_mutation","numero_disposition"], maintain_order=True).agg(pl.col("type_local"))

In [22]:
local_df.sample(5)

shape: (5, 3)
┌──────────────┬────────────────────┬───────────────────────────────┐
│ id_mutation  ┆ numero_disposition ┆ type_local                    │
│ ---          ┆ ---                ┆ ---                           │
│ str          ┆ i64                ┆ list[str]                     │
╞══════════════╪════════════════════╪═══════════════════════════════╡
│ 2024-1214195 ┆ 1                  ┆ ["Dépendance", "Appartement"] │
│ 2025-499491  ┆ 1                  ┆ ["Dépendance", "Appartement"] │
│ 2022-1687861 ┆ 1                  ┆ ["Dépendance", "Appartement"] │
│ 2022-1687833 ┆ 1                  ┆ ["Appartement", "Dépendance"] │
│ 2022-1683067 ┆ 1                  ┆ ["Appartement", "Dépendance"] │
└──────────────┴────────────────────┴───────────────────────────────┘

In [12]:
local_df = local_df.with_columns(
    pl.col("type_local").list.len()
    .alias("nb_biens"),
    pl.col("type_local").list.unique()
    .alias("type_biens_unique")
)
local_df

shape: (124_455, 5)
┌─────────────┬────────────────────┬─────────────────────┬──────────┬─────────────────────┐
│ id_mutation ┆ numero_disposition ┆ type_local          ┆ nb_biens ┆ type_biens_unique   │
│ ---         ┆ ---                ┆ ---                 ┆ ---      ┆ ---                 │
│ str         ┆ i64                ┆ list[str]           ┆ u32      ┆ list[str]           │
╞═════════════╪════════════════════╪═════════════════════╪══════════╪═════════════════════╡
│ 2020-815165 ┆ 1                  ┆ ["Indisponible"]    ┆ 1        ┆ ["Indisponible"]    │
│ 2020-814507 ┆ 1                  ┆ ["Dépendance"]      ┆ 1        ┆ ["Dépendance"]      │
│ 2020-814508 ┆ 1                  ┆ ["Appartement"]     ┆ 1        ┆ ["Appartement"]     │
│ 2020-814509 ┆ 1                  ┆ ["Dépendance"]      ┆ 1        ┆ ["Dépendance"]      │
│ 2020-814510 ┆ 1                  ┆ ["Appartement"]     ┆ 1        ┆ ["Appartement"]     │
│ …           ┆ …                  ┆ …                   ┆ …        ┆ …                   │
│ 2025-502878 ┆ 1                  ┆ ["Local industriel. ┆ 1        ┆ ["Local industriel. │
│             ┆                    ┆ commercial…         ┆          ┆ commercial…         │
│ 2025-502879 ┆ 2                  ┆ ["Local industriel. ┆ 3        ┆ ["Local industriel. │
│             ┆                    ┆ commercial…         ┆          ┆ commercial…         │
│ 2025-502880 ┆ 1                  ┆ ["Dépendance",      ┆ 2        ┆ ["Dépendance",      │
│             ┆                    ┆ "Appartement"]      ┆          ┆ "Appartement"]      │
│ 2025-502881 ┆ 1                  ┆ ["Appartement",     ┆ 2        ┆ ["Dépendance",      │
│             ┆                    ┆ "Dépendance"]       ┆          ┆ "Appartement"]      │
│ 2025-502882 ┆ 1                  ┆ ["Indisponible"]    ┆ 1        ┆ ["Indisponible"]    │
└─────────────┴────────────────────┴─────────────────────┴──────────┴─────────────────────┘

In [13]:
local_df = local_df.with_columns(
    pl.when(pl.col("type_biens_unique").list.contains("Appartement"))
    .then(True)
    .otherwise(False)
    .alias("has_appartement"),

    pl.when(pl.col("type_biens_unique").list.contains("Maison"))
    .then(True)
    .otherwise(False)
    .alias("has_maison"),

    pl.when(pl.col("type_biens_unique").list.contains("Dépendance"))
    .then(True)
    .otherwise(False)
    .alias("has_dependance")
)
local_df

shape: (124_455, 8)
┌────────────┬────────────┬────────────┬──────────┬────────────┬───────────┬───────────┬───────────┐
│ id_mutatio ┆ numero_dis ┆ type_local ┆ nb_biens ┆ type_biens ┆ has_appar ┆ has_maiso ┆ has_depen │
│ n          ┆ position   ┆ ---        ┆ ---      ┆ _unique    ┆ tement    ┆ n         ┆ dance     │
│ ---        ┆ ---        ┆ list[str]  ┆ u32      ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ i64        ┆            ┆          ┆ list[str]  ┆ bool      ┆ bool      ┆ bool      │
╞════════════╪════════════╪════════════╪══════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2020-81516 ┆ 1          ┆ ["Indispon ┆ 1        ┆ ["Indispon ┆ false     ┆ false     ┆ false     │
│ 5          ┆            ┆ ible"]     ┆          ┆ ible"]     ┆           ┆           ┆           │
│ 2020-81450 ┆ 1          ┆ ["Dépendan ┆ 1        ┆ ["Dépendan ┆ false     ┆ false     ┆ true      │
│ 7          ┆            ┆ ce"]       ┆          ┆ ce"]       ┆           ┆           ┆           │
│ 2020-81450 ┆ 1          ┆ ["Appartem ┆ 1        ┆ ["Appartem ┆ true      ┆ false     ┆ false     │
│ 8          ┆            ┆ ent"]      ┆          ┆ ent"]      ┆           ┆           ┆           │
│ 2020-81450 ┆ 1          ┆ ["Dépendan ┆ 1        ┆ ["Dépendan ┆ false     ┆ false     ┆ true      │
│ 9          ┆            ┆ ce"]       ┆          ┆ ce"]       ┆           ┆           ┆           │
│ 2020-81451 ┆ 1          ┆ ["Appartem ┆ 1        ┆ ["Appartem ┆ true      ┆ false     ┆ false     │
│ 0          ┆            ┆ ent"]      ┆          ┆ ent"]      ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …        ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2025-50287 ┆ 1          ┆ ["Local    ┆ 1        ┆ ["Local    ┆ false     ┆ false     ┆ false     │
│ 8          ┆            ┆ industriel ┆          ┆ industriel ┆           ┆           ┆           │
│            ┆            ┆ . commerci ┆          ┆ . commerci ┆           ┆           ┆           │
│            ┆            ┆ al…        ┆          ┆ al…        ┆           ┆           ┆           │
│ 2025-50287 ┆ 2          ┆ ["Local    ┆ 3        ┆ ["Local    ┆ false     ┆ false     ┆ false     │
│ 9          ┆            ┆ industriel ┆          ┆ industriel ┆           ┆           ┆           │
│            ┆            ┆ . commerci ┆          ┆ . commerci ┆           ┆           ┆           │
│            ┆            ┆ al…        ┆          ┆ al…        ┆           ┆           ┆           │
│ 2025-50288 ┆ 1          ┆ ["Dépendan ┆ 2        ┆ ["Dépendan ┆ true      ┆ false     ┆ true      │
│ 0          ┆            ┆ ce", "Appa ┆          ┆ ce", "Appa ┆           ┆           ┆           │
│            ┆            ┆ rtement"]  ┆          ┆ rtement"]  ┆           ┆           ┆           │
│ 2025-50288 ┆ 1          ┆ ["Appartem ┆ 2        ┆ ["Dépendan ┆ true      ┆ false     ┆ true      │
│ 1          ┆            ┆ ent", "Dép ┆          ┆ ce", "Appa ┆           ┆           ┆           │
│            ┆            ┆ endance"]  ┆          ┆ rtement"]  ┆           ┆           ┆           │
│ 2025-50288 ┆ 1          ┆ ["Indispon ┆ 1        ┆ ["Indispon ┆ false     ┆ false     ┆ false     │
│ 2          ┆            ┆ ible"]     ┆          ┆ ible"]     ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴──────────┴────────────┴───────────┴───────────┴───────────┘

In [14]:
appart = ["Appartement","Dépendance"]
maison = ["Maison","Dépendance"]
mixte = ["Appartement","Maison","Dépendance"]

In [15]:
local_df = local_df.with_columns(
    pl.when(
        (pl.col("type_biens_unique").list.contains("Appartement")) 
        &
        (pl.col("type_biens_unique").list.eval(pl.element().is_in(appart)).list.all())

    )
    .then(pl.lit("Appartement"))

    .when(
        (pl.col("type_biens_unique").list.contains("Maison"))
        &
        (pl.col("type_biens_unique").list.eval(pl.element().is_in(maison)).list.all())
    )
    .then(pl.lit("Maison"))

    .when(
        (pl.col("type_biens_unique").list.contains("Appartement"))
        &
        (pl.col("type_biens_unique").list.contains("Maison"))
        &
        (pl.col("type_biens_unique").list.eval(pl.element().is_in(mixte)).list.all())
    )
    .then(pl.lit("Mixte"))

    .when(
        (pl.col("type_biens_unique").list.contains("Indisponible"))
    )
    .then(pl.lit("Complex"))

    .otherwise(pl.lit("Autre"))
    .alias("type_bien_principal")
)

In [16]:
gold_transactions = gold_transactions.join(local_df.drop(["type_local","type_biens_unique"]),
                                           left_on=["id_mutation","numero_disposition"],
                                           right_on=["id_mutation","numero_disposition"],
                                           how="left",
                                           validate="m:1")

### 3. Colonne de date

In [17]:
gold_transactions = gold_transactions.with_columns(
    pl.col("date_mutation").dt.year().cast(pl.Int64).alias("annee")
)
gold_transactions

shape: (198_751, 30)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ id_mutatio ┆ date_mutat ┆ numero_dis ┆ nature_mu ┆ … ┆ has_maiso ┆ has_depen ┆ type_bien ┆ annee │
│ n          ┆ ion        ┆ position   ┆ tation    ┆   ┆ n         ┆ dance     ┆ _principa ┆ ---   │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ l         ┆ i64   │
│ str        ┆ date       ┆ i64        ┆ str       ┆   ┆ bool      ┆ bool      ┆ ---       ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ str       ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ 2020-81516 ┆ 2020-10-08 ┆ 1          ┆ Vente     ┆ … ┆ false     ┆ false     ┆ Complex   ┆ 2020  │
│ 5          ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 2020-81450 ┆ 2020-07-02 ┆ 1          ┆ Vente     ┆ … ┆ false     ┆ true      ┆ Autre     ┆ 2020  │
│ 7          ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 2020-81450 ┆ 2020-07-01 ┆ 1          ┆ Vente     ┆ … ┆ false     ┆ false     ┆ Apparteme ┆ 2020  │
│ 8          ┆            ┆            ┆           ┆   ┆           ┆           ┆ nt        ┆       │
│ 2020-81450 ┆ 2020-07-01 ┆ 1          ┆ Vente     ┆ … ┆ false     ┆ true      ┆ Autre     ┆ 2020  │
│ 9          ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
│ 2020-81451 ┆ 2020-07-01 ┆ 1          ┆ Vente     ┆ … ┆ false     ┆ false     ┆ Apparteme ┆ 2020  │
│ 0          ┆            ┆            ┆           ┆   ┆           ┆           ┆ nt        ┆       │
│ …          ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …     │
│ 2025-50288 ┆ 2025-06-27 ┆ 1          ┆ Vente     ┆ … ┆ false     ┆ true      ┆ Apparteme ┆ 2025  │
│ 0          ┆            ┆            ┆           ┆   ┆           ┆           ┆ nt        ┆       │
│ 2025-50288 ┆ 2025-06-27 ┆ 1          ┆ Vente     ┆ … ┆ false     ┆ true      ┆ Apparteme ┆ 2025  │
│ 0          ┆            ┆            ┆           ┆   ┆           ┆           ┆ nt        ┆       │
│ 2025-50288 ┆ 2025-06-27 ┆ 1          ┆ Vente     ┆ … ┆ false     ┆ true      ┆ Apparteme ┆ 2025  │
│ 1          ┆            ┆            ┆           ┆   ┆           ┆           ┆ nt        ┆       │
│ 2025-50288 ┆ 2025-06-27 ┆ 1          ┆ Vente     ┆ … ┆ false     ┆ true      ┆ Apparteme ┆ 2025  │
│ 1          ┆            ┆            ┆           ┆   ┆           ┆           ┆ nt        ┆       │
│ 2025-50288 ┆ 2025-06-25 ┆ 1          ┆ Vente     ┆ … ┆ false     ┆ false     ┆ Complex   ┆ 2025  │
│ 2          ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

### 4. Arrangement des colonnes

In [19]:
gold_transactions = gold_transactions.filter(
    (pl.col("is_valeur_fonciere_missing") == False) 
    & 
    (pl.col("is_surface_missing") == False)
    &
    (pl.col("is_transaction_atypique_agent") == False)
)
gold_transactions.shape

(113412, 30)

In [21]:
gold_transactions = gold_transactions[
    "id_mutation",
    "date_mutation",
    "annee",
    "numero_disposition",
    "nature_mutation",
    "valeur_fonciere",
    "prix_m2",
    "adresse_numero",
    "adresse_nom_voie",
    "code_postal",
    "type_local",
    "type_bien_principal",
    "surface_reelle_bati",
    "surface_totale",
    "nombre_pieces_principales",
    "has_appartement",
    "has_maison",
    "has_dependance",
    "is_valeur_fonciere_missing",
    "is_surface_missing",
    "is_nombre_pieces_missing",
    "is_appartement_sans_lot",
    "is_transaction_atypique_agent"
]

***

# Construction gold_market_metrics

In [22]:
gold_market_metrics = gold_transactions.unique(subset=["id_mutation","numero_disposition"], maintain_order=True)

In [24]:
gold_market_metrics.head(10)

shape: (10, 23)
┌────────────┬────────────┬───────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id_mutatio ┆ date_mutat ┆ annee ┆ numero_dis ┆ … ┆ is_surfac ┆ is_nombre ┆ is_appart ┆ is_transa │
│ n          ┆ ion        ┆ ---   ┆ position   ┆   ┆ e_missing ┆ _pieces_m ┆ ement_san ┆ ction_aty │
│ ---        ┆ ---        ┆ i64   ┆ ---        ┆   ┆ ---       ┆ issing    ┆ s_lot     ┆ pique_age │
│ str        ┆ date       ┆       ┆ i64        ┆   ┆ str       ┆ ---       ┆ ---       ┆ nt        │
│            ┆            ┆       ┆            ┆   ┆           ┆ str       ┆ str       ┆ ---       │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆ str       │
╞════════════╪════════════╪═══════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2020-81450 ┆ 2020-07-01 ┆ 2020  ┆ 1          ┆ … ┆ false     ┆ false     ┆ false     ┆ false     │
│ 8          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ 2020-81451 ┆ 2020-07-01 ┆ 2020  ┆ 1          ┆ … ┆ false     ┆ false     ┆ false     ┆ false     │
│ 0          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ 2020-81451 ┆ 2020-07-06 ┆ 2020  ┆ 1          ┆ … ┆ false     ┆ false     ┆ false     ┆ false     │
│ 4          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ 2020-81451 ┆ 2020-07-02 ┆ 2020  ┆ 1          ┆ … ┆ false     ┆ false     ┆ false     ┆ false     │
│ 5          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ 2020-81451 ┆ 2020-07-02 ┆ 2020  ┆ 1          ┆ … ┆ false     ┆ false     ┆ false     ┆ false     │
│ 7          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ 2020-81451 ┆ 2020-07-01 ┆ 2020  ┆ 2          ┆ … ┆ false     ┆ false     ┆ false     ┆ false     │
│ 8          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ 2020-81452 ┆ 2020-07-03 ┆ 2020  ┆ 1          ┆ … ┆ false     ┆ false     ┆ false     ┆ false     │
│ 0          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ 2020-81452 ┆ 2020-07-06 ┆ 2020  ┆ 1          ┆ … ┆ false     ┆ false     ┆ false     ┆ false     │
│ 1          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ 2020-81452 ┆ 2020-07-09 ┆ 2020  ┆ 1          ┆ … ┆ false     ┆ false     ┆ false     ┆ false     │
│ 2          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ 2020-81452 ┆ 2020-07-03 ┆ 2020  ┆ 1          ┆ … ┆ false     ┆ false     ┆ false     ┆ false     │
│ 3          ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴───────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [25]:
gold_market_metrics = (
    gold_market_metrics
    .group_by(["code_postal","type_bien_principal","annee"])
    .agg(
        pl.count("id_mutation").alias("nb_transactions"),
        pl.mean("prix_m2").alias("prix_m2_mean"),
        pl.median("prix_m2").alias("prix_m2_median"),
        pl.quantile("prix_m2", 0.25).alias("prix_m2_q25"),
        pl.quantile("prix_m2", 0.75).alias("prix_m2_q75"),
        pl.median("valeur_fonciere").alias("valeur_fonciere_median"),
        pl.mean("surface_totale").alias("surface_mean"),
        pl.median("surface_totale").alias("surface_median")
        )
    )

In [26]:
gold_market_metrics

shape: (396, 11)
┌────────────┬────────────┬───────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ code_posta ┆ type_bien_ ┆ annee ┆ nb_transac ┆ … ┆ prix_m2_q ┆ valeur_fo ┆ surface_m ┆ surface_m │
│ l          ┆ principal  ┆ ---   ┆ tions      ┆   ┆ 75        ┆ nciere_me ┆ ean       ┆ edian     │
│ ---        ┆ ---        ┆ i64   ┆ ---        ┆   ┆ ---       ┆ dian      ┆ ---       ┆ ---       │
│ str        ┆ str        ┆       ┆ u32        ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│            ┆            ┆       ┆            ┆   ┆           ┆ f64       ┆           ┆           │
╞════════════╪════════════╪═══════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 75016      ┆ Appartemen ┆ 2022  ┆ 1909       ┆ … ┆ 13613.272 ┆ 790000.0  ┆ 88.762703 ┆ 74.0      │
│            ┆ t          ┆       ┆            ┆   ┆ 727       ┆           ┆           ┆           │
│ 75009      ┆ Appartemen ┆ 2023  ┆ 351        ┆ … ┆ 12391.304 ┆ 436500.0  ┆ 53.444444 ┆ 46.0      │
│            ┆ t          ┆       ┆            ┆   ┆ 348       ┆           ┆           ┆           │
│ 75003      ┆ Complex    ┆ 2021  ┆ 1          ┆ … ┆ 25.323276 ┆ 47000.0   ┆ 1856.0    ┆ 1856.0    │
│ 75019      ┆ Maison     ┆ 2025  ┆ 7          ┆ … ┆ 20708.791 ┆ 1.5585e6  ┆ 86.714286 ┆ 91.0      │
│            ┆            ┆       ┆            ┆   ┆ 209       ┆           ┆           ┆           │
│ 75004      ┆ Autre      ┆ 2020  ┆ 34         ┆ … ┆ 16000.0   ┆ 656000.0  ┆ 173.70588 ┆ 105.5     │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ 2         ┆           │
│ …          ┆ …          ┆ …     ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 75012      ┆ Appartemen ┆ 2023  ┆ 1429       ┆ … ┆ 10522.448 ┆ 370000.0  ┆ 46.940518 ┆ 41.0      │
│            ┆ t          ┆       ┆            ┆   ┆ 98        ┆           ┆           ┆           │
│ 75011      ┆ Complex    ┆ 2021  ┆ 1          ┆ … ┆ 12977.419 ┆ 804600.0  ┆ 62.0      ┆ 62.0      │
│            ┆            ┆       ┆            ┆   ┆ 355       ┆           ┆           ┆           │
│ 75010      ┆ Autre      ┆ 2022  ┆ 24         ┆ … ┆ 10476.190 ┆ 779100.0  ┆ 228.75    ┆ 133.5     │
│            ┆            ┆       ┆            ┆   ┆ 476       ┆           ┆           ┆           │
│ 75014      ┆ Maison     ┆ 2022  ┆ 11         ┆ … ┆ 15198.198 ┆ 1.918653e ┆ 133.0     ┆ 127.0     │
│            ┆            ┆       ┆            ┆   ┆ 198       ┆ 6         ┆           ┆           │
│ 75006      ┆ Complex    ┆ 2020  ┆ 1          ┆ … ┆ 1.4667e7  ┆ 1.76e8    ┆ 12.0      ┆ 12.0      │
└────────────┴────────────┴───────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

***

# Construction gold_location_features

In [27]:
bpe_silver

shape: (3_773, 6)
┌───────┬─────────────┬───────────────────┬──────────────────┬──────────────────┬──────────────────┐
│ annee ┆ code_postal ┆ classification_n1 ┆ classification_n ┆ classification_n ┆ nombre_equipemen │
│ ---   ┆ ---         ┆ ---               ┆ 2                ┆ 3                ┆ ts               │
│ i64   ┆ str         ┆ str               ┆ ---              ┆ ---              ┆ ---              │
│       ┆             ┆                   ┆ str              ┆ str              ┆ i64              │
╞═══════╪═════════════╪═══════════════════╪══════════════════╪══════════════════╪══════════════════╡
│ 2024  ┆ 75004       ┆ Santé et action   ┆ Fonctions        ┆ Spécialiste en   ┆ 26               │
│       ┆             ┆ sociale           ┆ médicales et     ┆ cardiologie      ┆                  │
│       ┆             ┆                   ┆ paraméd…         ┆                  ┆                  │
│ 2024  ┆ 75004       ┆ Commerces         ┆ Commerces        ┆ Station de       ┆ 13               │
│       ┆             ┆                   ┆ spécialisés      ┆ recharge de      ┆                  │
│       ┆             ┆                   ┆ non-alim…        ┆ véhicul…         ┆                  │
│ 2024  ┆ 75003       ┆ Santé et action   ┆ Fonctions        ┆ Spécialiste en   ┆ 4                │
│       ┆             ┆ sociale           ┆ médicales et     ┆ pédiatrie        ┆                  │
│       ┆             ┆                   ┆ paraméd…         ┆                  ┆                  │
│ 2024  ┆ 75014       ┆ Santé et action   ┆ Fonctions        ┆ Spécialiste en   ┆ 38               │
│       ┆             ┆ sociale           ┆ médicales et     ┆ oncologie, anat… ┆                  │
│       ┆             ┆                   ┆ paraméd…         ┆                  ┆                  │
│ 2024  ┆ 75010       ┆ Commerces         ┆ Commerces        ┆ Supérette        ┆ 26               │
│       ┆             ┆                   ┆ alimentaires     ┆                  ┆                  │
│ …     ┆ …           ┆ …                 ┆ …                ┆ …                ┆ …                │
│ 2024  ┆ 75020       ┆ Commerces         ┆ Commerces        ┆ Total            ┆ 630              │
│       ┆             ┆                   ┆ spécialisés      ┆                  ┆                  │
│       ┆             ┆                   ┆ non-alim…        ┆                  ┆                  │
│ 2024  ┆ 75016       ┆ Commerces         ┆ Commerces        ┆ Total            ┆ 422              │
│       ┆             ┆                   ┆ alimentaires     ┆                  ┆                  │
│ 2024  ┆ 75012       ┆ Enseignement      ┆ Autres services  ┆ Total            ┆ 6                │
│       ┆             ┆                   ┆ de l'éducation   ┆                  ┆                  │
│ 2024  ┆ 75013       ┆ Total             ┆ Total            ┆ Total            ┆ 6657             │
│ 2024  ┆ 75009       ┆ Santé et action   ┆ Autres services  ┆ Total            ┆ 21               │
│       ┆             ┆ sociale           ┆ d'action socia…  ┆                  ┆                  │
└───────┴─────────────┴───────────────────┴──────────────────┴──────────────────┴──────────────────┘

In [23]:
gold_location_features = bpe_silver.clone()

In [24]:
gold_location_features = gold_location_features.with_columns(
    pl.when((pl.col("classification_n1") == "Santé et action sociale") 
            &
            (pl.col("classification_n2") != "Total")
            &
            (pl.col("classification_n3") != "Total")
            )
    .then(pl.col("nombre_equipements"))
    .otherwise(pl.lit(0))
    .alias("nb_sante")
    ,

    pl.when((pl.col("classification_n1") == "Enseignement")
            &
            (pl.col("classification_n2") != "Total")
            &
            (pl.col("classification_n3") != "Total")
            )
    .then(pl.col("nombre_equipements"))
    .otherwise(pl.lit(0))
    .alias("nb_enseignement")
    ,

    pl.when((pl.col("classification_n2") == "Services publics")
            &
            (pl.col("classification_n3") != "Total")
            )
    .then(pl.col("nombre_equipements"))
    .otherwise(pl.lit(0))
    .alias("nb_services_publics")
    ,

    pl.when((pl.col("classification_n1") == "Transports et déplacements")
            &
            (pl.col("classification_n2") != "Total")
            &
            (pl.col("classification_n3") != "Total")
            )
    .then(pl.col("nombre_equipements"))
    .otherwise(pl.lit(0))
    .alias("nb_transports")
    ,

    pl.when((pl.col("classification_n1") == "Commerces")
            &
            (pl.col("classification_n2") != "Total")
            &
            (pl.col("classification_n3") != "Total")
            )
    .then(pl.col("nombre_equipements"))
    .otherwise(pl.lit(0))
    .alias("nb_commerces")
    ,

    pl.when((pl.col("classification_n1") == "Sports, loisirs et culture")
            &
            (pl.col("classification_n2") != "Total")
            &
            (pl.col("classification_n3") != "Total")
            )
    .then(pl.col("nombre_equipements"))
    .otherwise(pl.lit(0))
    .alias("nb_sports_loisirs")
)

In [25]:
gold_location_features = (
    gold_location_features
    .group_by(["annee","code_postal"])
    .agg(
        pl.sum("nb_sante"),
        pl.sum("nb_enseignement"),
        pl.sum("nb_services_publics"),
        pl.sum("nb_transports"),
        pl.sum("nb_commerces"),
        pl.sum("nb_sports_loisirs")
    )
)

In [42]:
equipment_cols = [
    "nb_sante",
    "nb_enseignement",
    "nb_services_publics",
    "nb_transports",
    "nb_commerces",
    "nb_sports_loisirs"
]

weights = {
    "nb_sante": 0.25,
    "nb_enseignement": 0.20,
    "nb_transports": 0.20,
    "nb_commerces": 0.15,
    "nb_sports_loisirs": 0.10,
    "nb_services_publics": 0.10,
}

In [43]:
data = {"code_postal": ["75001","75002","75003","75004","75005","75006","75007","75008","75009","75010","75011","75012","75013","75014","75015","75016","75017","75018","75019","75020"],
        "surface_km2": [1.824613, 0.991154, 1.170883, 1.600586, 2.539375, 2.153096, 4.090057, 3.880036, 2.178303, 2.891739, 3.665442, 16.314783, 7.149311, 5.614877, 8.494994, 16.372542, 5.668835, 5.996051, 6.792651, 5.983446]
        }

In [44]:
surface_km2 = pl.DataFrame(data)

In [45]:
gold_location_features = gold_location_features.join(surface_km2,
                                                     on="code_postal",
                                                     how="left")

In [47]:
gold_location_features = (
    gold_location_features
    .with_columns([
        (
            pl.col(col) / pl.col("surface_km2")
        )
        .log1p()
        .alias(f"{col}_densite_log")
        for col in equipment_cols
    ])
    .with_columns([
        (
            (pl.col(f"{col}_densite_log") - pl.col(f"{col}_densite_log").min().over("annee"))
            / 
            (pl.col(f"{col}_densite_log").max().over("annee") - pl.col(f"{col}_densite_log").min().over("annee"))
        )
        .fill_nan(0)
        .alias(f"{col}_score")
        for col in equipment_cols
    ])
    .with_columns(
        (
            100 * sum(
                pl.col(f"{col}_score") * weight
                for col, weight in weights.items()
            )
        )
        .round(2)
        .alias("score_equipements")
    )
    .drop([f"{col}_densite_log" for col in equipment_cols])
    .drop([f"{col}_score" for col in equipment_cols])
)

In [51]:
gold_location_features.head(10)

shape: (10, 10)
┌───────┬────────────┬──────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ annee ┆ code_posta ┆ nb_sante ┆ nb_enseign ┆ … ┆ nb_commerc ┆ nb_sports_ ┆ surface_k ┆ score_equ │
│ ---   ┆ l          ┆ ---      ┆ ement      ┆   ┆ es         ┆ loisirs    ┆ m2        ┆ ipements  │
│ i64   ┆ ---        ┆ i64      ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│       ┆ str        ┆          ┆ i64        ┆   ┆ i64        ┆ i64        ┆ f64       ┆ f64       │
╞═══════╪════════════╪══════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 2024  ┆ 75019      ┆ 1575     ┆ 203        ┆ … ┆ 1098       ┆ 136        ┆ 6.792651  ┆ 51.84     │
│ 2024  ┆ 75004      ┆ 508      ┆ 41         ┆ … ┆ 919        ┆ 44         ┆ 1.600586  ┆ 62.66     │
│ 2024  ┆ 75003      ┆ 527      ┆ 74         ┆ … ┆ 918        ┆ 33         ┆ 1.170883  ┆ 81.6      │
│ 2024  ┆ 75014      ┆ 1839     ┆ 141        ┆ … ┆ 1064       ┆ 138        ┆ 5.614877  ┆ 55.32     │
│ 2024  ┆ 75001      ┆ 385      ┆ 35         ┆ … ┆ 1282       ┆ 32         ┆ 1.824613  ┆ 57.88     │
│ 2024  ┆ 75013      ┆ 1994     ┆ 237        ┆ … ┆ 980        ┆ 175        ┆ 7.149311  ┆ 53.44     │
│ 2024  ┆ 75009      ┆ 1145     ┆ 92         ┆ … ┆ 1499       ┆ 66         ┆ 2.178303  ┆ 79.71     │
│ 2024  ┆ 75010      ┆ 977      ┆ 135        ┆ … ┆ 1555       ┆ 69         ┆ 2.891739  ┆ 73.68     │
│ 2024  ┆ 75012      ┆ 1862     ┆ 168        ┆ … ┆ 1223       ┆ 183        ┆ 16.314783 ┆ 8.38      │
│ 2024  ┆ 75008      ┆ 1383     ┆ 105        ┆ … ┆ 2253       ┆ 56         ┆ 3.880036  ┆ 69.18     │
└───────┴────────────┴──────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [33]:
test = gold_location_features.clone()